# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4699cea5b1be69fbd95f6b271000e1fbaac9057fc4fe9a34107e87b6e904762089279b0eb71cee77e7cfde36fc3b9e7e302f7e6efd8a836f9effe1ef88064fbd

test:
  secret_key_base: 47d9775de64217b4ee7464e473d272055a147cdd6315dffd5a7827a6e8e76913ab2f1af4557bb6a1f84f3fe149269f13b68a463d50fbfdcb3988f27c9c90c11f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
